version: "3"

vars:
  GOEXE:
    sh: go env GOEXE

tasks:
  run:
    cmds:
      - go run ./cmd/server {{.CLI_ARGS}}

  build:
    cmds:
      - go build {{.CLI_ARGS}} -o bin/server{{.GOEXE}} ./cmd/server

  fmt:
    cmds:
      - gofmt -w .

  fmt:check:
    cmds:
      - test -z "$(gofmt -l .)"

  vet:
    cmds:
      - go vet ./...

  tidy:
    cmds:
      - go mod tidy

  check:
    cmds:
      - task: fmt:check
      - task: vet
