package adapters

import (
	"strings"

	"github.com/torchstellar-team/one-cli/packages/cli/pkg/toolchain"
)

// goAdapter implements toolchain.Adapter for Go subprojects.
type goAdapter struct{}

func (goAdapter) ID() toolchain.Toolchain  { return toolchain.Go }
func (goAdapter) UsesPackageManager() bool { return false }

func (goAdapter) InstallPlan(_ toolchain.PlanInput) toolchain.CommandStep {
	return toolchain.CommandStep{
		Kind:    "install",
		Command: "go",
		Args:    []string{"mod", "tidy"},
	}
}

// PackageManagerForManifest returns empty for Go: the manifest field is
// omitted because Go subprojects have no package manager.
func (goAdapter) PackageManagerForManifest(_ toolchain.PackageManager) toolchain.PackageManager {
	return ""
}

func (goAdapter) ResolveRuntime(_ toolchain.PlanInput) toolchain.RuntimeResolution {
	// Hard-coded values mirror the TS adapter — every Go template builds
	// to /app/server and exposes 3000.
	return toolchain.RuntimeResolution{
		RunCommand:    "/app/server",
		ContainerPort: 3000,
	}
}

func (goAdapter) RenderDockerfile(in toolchain.DockerfileInput) string {
	// Go template Dockerfiles are static; only the EXPOSE port varies.
	return `# Generated by One CLI
FROM golang:1.26-alpine AS builder

WORKDIR /workspace
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/server ./cmd/server

FROM alpine:3.22

RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /out/server /app/server

EXPOSE ` + intToString(in.Runtime.ContainerPort) + `
CMD ["/app/server"]
`
}

func (goAdapter) RenderWorkflow(in toolchain.WorkflowInput) string {
	lines := workflowHeader(in.ProjectName, in.RelativeDir, in.WorkflowFilePath)
	lines = append(lines,
		"      - uses: actions/setup-go@v5",
		"        with:",
		"          go-version: '1.26'",
		"          cache: false",
		"      - uses: go-task/setup-task@v2",
		"      - name: Run checks",
		"        run: task check",
		"      - name: Build",
		"        run: task build",
	)
	return strings.Join(lines, "\n") + "\n"
}

// workflowHeader is the YAML preamble shared by both toolchains. Mirrors
// renderWorkflowHeader in TS.
func workflowHeader(projectName, relativeDir, workflowFilePath string) []string {
	return []string{
		"# Generated by One CLI",
		"name: CI - " + projectName,
		"",
		"on:",
		"  pull_request:",
		"    paths:",
		"      - '" + relativeDir + "/**'",
		"      - '" + workflowFilePath + "'",
		"  push:",
		"    paths:",
		"      - '" + relativeDir + "/**'",
		"      - '" + workflowFilePath + "'",
		"  workflow_dispatch:",
		"",
		"jobs:",
		"  ci:",
		"    runs-on: ubuntu-latest",
		"    defaults:",
		"      run:",
		"        working-directory: ./" + relativeDir,
		"    steps:",
		"      - uses: actions/checkout@v4",
	}
}

// intToString avoids strconv import noise in node.go which doesn't need it.
func intToString(n int) string {
	// Tiny stdlib-free conversion (n is always positive and small here).
	if n == 0 {
		return "0"
	}
	digits := []byte{}
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	return string(digits)
}
