// Package adapters bundles One CLI's built-in toolchain adapters. The
// composition root calls RegisterBundled explicitly; importing this package
// has no side effects. Consumers use pkg/toolchain for the public contract.
package adapters

import (
	"fmt"
	"strings"

	"github.com/torchstellar-team/one-cli/packages/cli/pkg/toolchain"
)

// nodeAdapter implements toolchain.Adapter for Node.js subprojects (the
// default).
type nodeAdapter struct{}

func (nodeAdapter) ID() toolchain.Toolchain  { return toolchain.Node }
func (nodeAdapter) UsesPackageManager() bool { return true }

func (nodeAdapter) InstallPlan(in toolchain.PlanInput) toolchain.CommandStep {
	pm := resolvePackageManager(in.PackageManager)
	return toolchain.CommandStep{
		Kind:    "install",
		Command: string(pm),
		Args:    []string{"install"},
	}
}

// PackageManagerForManifest just echoes the value back for Node — every
// Node template has a meaningful package manager. Go's adapter returns "" so
// the manifest omits the field for go subprojects.
func (nodeAdapter) PackageManagerForManifest(pm toolchain.PackageManager) toolchain.PackageManager {
	if pm == "" {
		return toolchain.PMpnpm
	}
	return pm
}

func (nodeAdapter) ResolveRuntime(in toolchain.PlanInput) toolchain.RuntimeResolution {
	pm := resolvePackageManager(in.PackageManager)
	scripts := in.Scripts
	if scripts == nil {
		scripts = map[string]string{}
	}
	templateID := in.TemplateID
	if templateID == "" {
		templateID = "custom"
	}
	candidate, port, ok := pickRuntimeCandidate(scripts, templateID)
	if !ok {
		return toolchain.RuntimeResolution{
			RunCommand:    `node -e "console.error('No runnable script found. Update Dockerfile CMD manually.'); process.exit(1)"`,
			ContainerPort: defaultRuntimePreset.ContainerPort,
		}
	}
	base := resolveRunScriptCommand(pm, candidate.Script, "")
	return toolchain.RuntimeResolution{
		RunCommand:    base + candidate.Args,
		ContainerPort: port,
	}
}

func (nodeAdapter) RenderDockerfile(in toolchain.DockerfileInput) string {
	pm := resolvePackageManager(in.PackageManager)
	return fmt.Sprintf(`# Generated by One CLI
FROM node:20-alpine

WORKDIR /workspace
RUN corepack enable

COPY package.json ./
COPY pnpm-lock.yaml* package-lock.json* yarn.lock* ./
RUN %s

COPY . .

EXPOSE %d
CMD ["sh", "-c", "%s"]
`, resolveNodeInstallCommand(pm, false), in.Runtime.ContainerPort, escapeForDoubleQuotedValue(in.Runtime.RunCommand))
}

func (nodeAdapter) RenderWorkflow(in toolchain.WorkflowInput) string {
	pm := resolvePackageManager(in.PackageManager)
	lockfile := resolveLockfileByPM(pm)
	installCmd := resolveNodeInstallCommand(pm, true)
	ciCmds := resolveNodeCiCommands(in.Scripts, pm)

	lines := workflowHeader(in.ProjectName, in.RelativeDir, in.WorkflowFilePath)

	if pm == toolchain.PMpnpm {
		lines = append(lines,
			"      - uses: pnpm/action-setup@v4",
			"        with:",
			"          version: 10",
		)
	}

	lines = append(lines,
		"      - uses: actions/setup-node@v4",
		"        with:",
		"          node-version: 20",
		"          cache: "+string(pm),
		"          cache-dependency-path: ./"+in.RelativeDir+"/"+lockfile,
		"      - name: Install dependencies",
		"        run: "+installCmd,
	)
	for _, cmd := range ciCmds {
		lines = append(lines,
			"      - name: Run "+cmd,
			"        run: "+cmd,
		)
	}
	return strings.Join(lines, "\n") + "\n"
}
