/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/app/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      backgroundImage: {},
      backgroundColor: {
        brand1: {
          1: "var(--brand1-1)",
          2: "var(--brand1-2)",
          3: "var(--brand1-3)",
          4: "var(--brand1-4)",
          5: "var(--brand1-5)",
          6: "var(--brand1-6)",
          7: "var(--brand1-7)",
        },
        brand2: {
          1: "var(--brand2-1)",
          2: "var(--brand2-2)",
          3: "var(--brand2-3)",
          4: "var(--brand2-4)",
          5: "var(--brand2-5)",
          6: "var(--brand2-6)",
          7: "var(--brand2-7)",
        },
        gray: {
          1: "var(--gray-1)",
          2: "var(--gray-2)",
          3: "var(--gray-3)",
          4: "var(--gray-4)",
          5: "var(--gray-5)",
          6: "var(--gray-6)",
          7: "var(--gray-7)",
          8: "var(--gray-8)",
          9: "var(--gray-9)",
          10: "var(--gray-10)",
          11: "var(--gray-11)",
        },
      },
      textColor: {
        brand1: {
          1: "var(--brand1-1)",
          2: "var(--brand1-2)",
          3: "var(--brand1-3)",
          4: "var(--brand1-4)",
          5: "var(--brand1-5)",
          6: "var(--brand1-6)",
          7: "var(--brand1-7)",
        },
        brand2: {
          1: "var(--brand2-1)",
          2: "var(--brand2-2)",
          3: "var(--brand2-3)",
          4: "var(--brand2-4)",
          5: "var(--brand2-5)",
          6: "var(--brand2-6)",
          7: "var(--brand2-7)",
        },
        gray: {
          1: "var(--gray-1)",
          2: "var(--gray-2)",
          3: "var(--gray-3)",
          4: "var(--gray-4)",
          5: "var(--gray-5)",
          6: "var(--gray-6)",
          7: "var(--gray-7)",
          8: "var(--gray-8)",
          9: "var(--gray-9)",
          10: "var(--gray-10)",
          11: "var(--gray-11)",
        },
        error: {
          1: "var(--error-1)",
          2: "var(--error-2)",
          3: "var(--error-3)",
          5: "var(--error-5)",
          6: "var(--error-6)",
          7: "var(--error-7)",
        },
      },
      borderRadius: {},
      borderColor: {
        brand1: {
          1: "var(--brand1-1)",
          2: "var(--brand1-2)",
          3: "var(--brand1-3)",
          4: "var(--brand1-4)",
          5: "var(--brand1-5)",
          6: "var(--brand1-6)",
          7: "var(--brand1-7)",
        },
        gray: {
          1: "var(--gray-1)",
          2: "var(--gray-2)",
          3: "var(--gray-3)",
          4: "var(--gray-4)",
          5: "var(--gray-5)",
          6: "var(--gray-6)",
          7: "var(--gray-7)",
          8: "var(--gray-8)",
          9: "var(--gray-9)",
          10: "var(--gray-10)",
          11: "var(--gray-11)",
        },
      },
      colors: {
        brand1: {
          1: "hsl(var(--brand1-1))",
          2: "hsl(var(--brand1-2))",
          3: "hsl(var(--brand1-3))",
          4: "hsl(var(--brand1-4))",
          5: "hsl(var(--brand1-5))",
          6: "hsl(var(--brand1-6))",
          7: "hsl(var(--brand1-7))",
        },
        brand2: {
          1: "hsl(var(--brand2-1))",
          2: "hsl(var(--brand2-2))",
          3: "hsl(var(--brand2-3))",
          4: "hsl(var(--brand2-4))",
          5: "hsl(var(--brand2-5))",
          6: "hsl(var(--brand2-6))",
          7: "hsl(var(--brand2-7))",
        },
        gray: {
          1: "hsl(var(--gray-1))",
          2: "hsl(var(--gray-2))",
          3: "hsl(var(--gray-3))",
          4: "hsl(var(--gray-4))",
          5: "hsl(var(--gray-5))",
          6: "hsl(var(--gray-6))",
          7: "hsl(var(--gray-7))",
          8: "hsl(var(--gray-8))",
          9: "hsl(var(--gray-9))",
          10: "hsl(var(--gray-10))",
          11: "hsl(var(--gray-11))",
        },
        mask: {
          1: "hsl(var(--mask-1))",
        },
        info: {
          1: "hsl(var(--info-1))",
          2: "hsl(var(--info-2))",
          3: "hsl(var(--info-3))",
          5: "hsl(var(--info-5))",
          6: "hsl(var(--info-6))",
          7: "hsl(var(--info-7))",
        },
        success: {
          1: "hsl(var(--success-1))",
          2: "hsl(var(--success-2))",
          3: "hsl(var(--success-3))",
          5: "hsl(var(--success-5))",
          6: "hsl(var(--success-6))",
          7: "hsl(var(--success-7))",
        },
        warning: {
          1: "hsl(var(--warning-1))",
          2: "hsl(var(--warning-2))",
          3: "hsl(var(--warning-3))",
          5: "hsl(var(--warning-5))",
          6: "hsl(var(--warning-6))",
          7: "hsl(var(--warning-7))",
        },
        error: {
          1: "hsl(var(--error-1))",
          2: "hsl(var(--error-2))",
          3: "hsl(var(--error-3))",
          5: "hsl(var(--error-5))",
          6: "hsl(var(--error-6))",
          7: "hsl(var(--error-7))",
        },
      },
      keyframes: {},
      animation: {},
      boxShadow: {},
    },
  },
  plugins: [],
};
