/**
 * Welcome screen — kept intentionally minimal for AI agents to extend.
 *
 * Pre-wired infrastructure (don't recreate; import from these paths):
 *   - Theme:         useConfigStore (src/store/config.ts)  — toggles 'light' / 'dark'
 *   - Theme color:   useThemeColor (src/hooks/useThemeColor.ts) + src/constants/colors.ts
 *   - Auth:          useAuth (src/hooks/useAuth.ts)        — userLogin(code) / userLogout()
 *   - HTTP client:   src/lib/axios.ts
 *   - Storage:       src/lib/mmkv.ts                        (synchronous, encrypted KV)
 *   - SWR setup:     src/hooks/setup/swr.ts
 *   - API modules:   src/api/{common,auth,token,index}.ts  — `key + fetcher` shape
 *   - Routing:       expo-router (src/app/, file-based)
 *   - Themed atoms:  ThemedView / ThemedText (src/components/) — read theme color from tokens
 *   - External link: ExternalLink (src/components/ExternalLink.tsx) — wraps expo-web-browser
 *   - Design tokens: src/constants/colors.ts + React Native StyleSheet
 *
 * Atomic design (advisory — physical folders NOT enforced):
 *   - atoms      → src/components/{ThemedView,ThemedText,ExternalLink}.tsx + ui/
 *   - molecules  → src/components/                (compose atoms; e.g. ResourceLink below)
 *   - organisms  → src/app/(tabs)/<screen>.tsx    (screens are organisms here)
 *   - pages      → src/app/                       (expo-router routes)
 *
 * Use StyleSheet.create for layout and useThemeColor for theme-aware colors.
 * Keep shared color values in src/constants/colors.ts.
 */

import React from "react";
import { Pressable, ScrollView, StyleSheet, View } from "react-native";
import { ThemedText } from "@/components/ThemedText";
import { ThemedView } from "@/components/ThemedView";
import { ExternalLink } from "@/components/ExternalLink";
import { BrandColors } from "@/constants/colors";
import { useThemeColor } from "@/hooks/useThemeColor";

export default function HomeScreen() {
  const mutedText = useThemeColor({}, "mutedText");
  const borderColor = useThemeColor({}, "border");
  const tintColor = useThemeColor({}, "tint");

  return (
    <ThemedView style={styles.screen}>
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.brand}>
          <ThemedText style={styles.brandText}>ONE CLI</ThemedText>
        </View>

        <ThemedText type="title" style={styles.title}>
          Welcome to One CLI
        </ThemedText>
        <ThemedText style={[styles.stack, { color: mutedText }]}>EXPO · REACT NATIVE</ThemedText>
        <ThemedText style={[styles.description, { color: mutedText }]}>
          由 One CLI 生成的 Expo 移动端脚手架，预置原生样式、SWR、MMKV 与主题颜色。
          {"\n"}
          An Expo starter generated by One CLI with native styles, SWR, MMKV, and theme colors.
        </ThemedText>

        <ThemedText style={[styles.hint, { color: mutedText }]}>
          编辑 src/app/(tabs)/index.tsx 并保存以开始。{"\n"}
          Edit src/app/(tabs)/index.tsx and save to start.
        </ThemedText>

        <View style={styles.actions}>
          <ExternalLink href="https://1cli.dev/zh/docs/quick-start/" asChild>
            <Pressable style={[styles.button, { backgroundColor: tintColor }]}>
              <ThemedText style={[styles.buttonText, { color: BrandColors.buttonText }]}>
                开始构建 / Start building
              </ThemedText>
            </Pressable>
          </ExternalLink>
          <ExternalLink href="https://github.com/torchstellar-team/one-cli" asChild>
            <Pressable style={[styles.button, styles.secondaryButton, { borderColor }]}>
              <ThemedText style={styles.buttonText}>GitHub</ThemedText>
            </Pressable>
          </ExternalLink>
        </View>
      </ScrollView>
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 48,
  },
  brand: {
    borderRadius: 16,
    backgroundColor: BrandColors.background,
    paddingHorizontal: 24,
    paddingVertical: 16,
    marginBottom: 32,
  },
  brandText: {
    color: BrandColors.text,
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "500",
    letterSpacing: 4,
  },
  title: {
    marginBottom: 8,
    textAlign: "center",
  },
  stack: {
    marginBottom: 8,
    textAlign: "center",
    fontSize: 12,
    letterSpacing: 1.5,
  },
  description: {
    marginBottom: 24,
    maxWidth: 320,
    textAlign: "center",
  },
  hint: {
    marginBottom: 32,
    textAlign: "center",
    fontSize: 13,
  },
  actions: {
    width: "100%",
    maxWidth: 320,
    gap: 12,
  },
  button: {
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  secondaryButton: {
    borderWidth: 1,
  },
  buttonText: {
    textAlign: "center",
    fontWeight: "500",
  },
});
