package scaffold

import (
	"fmt"

	"github.com/torchstellar-team/one-cli/packages/cli/internal/workspace"
)

// These are the verbatim file contents the scaffolder writes.

const pnpmWorkspaceContent = `packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
`

const gitignoreContent = `# dependencies
node_modules

# build output
dist
coverage

# environment
.env
.env.local

# secrets — private keys must NEVER be committed
# (the .secrets/.gitignore inside the dir is the primary defense; this is
# a belt-and-suspenders entry for the workspace root)
.secrets/keys/

# misc
.DS_Store
`

const commitlintConfigContent = `module.exports = {
  extends: ['@commitlint/config-conventional']
};
`

const huskyPreCommitContent = `#!/usr/bin/env sh
echo "pre-commit hook: add checks for this repository."
`

const huskyCommitMsgContent = `#!/usr/bin/env sh
npx --no -- commitlint --edit "$1"
`

const dockerComposeContent = `services:
  # one-cli:services:start
  # one-cli:services:end
`

const k8sDeploymentContent = `# one-cli:resources:start
# one-cli:resources:end
`

// claudeMdTemplate is the workspace-level CLAUDE.md skeleton. It carries
// two managed blocks:
//
//   - <!-- one subprojects:start --> ... <!-- one subprojects:end -->
//     Filled by ai.UpdateSubprojectsIndex with a markdown table linking
//     to each sub-project's per-template CLAUDE.md. Updated on every
//     `one add`.
//
//   - <!-- one ai-guides:start --> ... <!-- one ai-guides:end -->
//     Filled by ai.Refresh — current workspaces render for every supported AI
//     provider, no opt-in needed. Stays as the placeholder text below
//     until at least one sub-project is scaffolded.
//
// Hand-written content OUTSIDE these markers is preserved by both
// renderers — readers can add workspace-specific rules above/below.
//
// %s is the workspace name (substituted by buildClaudeMd).
const claudeMdTemplate = `# %s — Agent Guide

This is the workspace-level guide. **Each sub-project has its own** ` + "`CLAUDE.md`" + ` **with stack-specific rules** — open the per-project file when working inside that sub-project.

## Sub-projects

The list below is regenerated by ` + "`one add`" + ` and ` + "`one ai refresh`" + `. Don't hand-edit between the markers — content outside is preserved.

<!-- one subprojects:start -->
*No sub-projects yet. Run* ` + "`one add <template-id> --name <name>`" + ` *to scaffold one (e.g. ` + "`one add react-spa --name web`" + `).*
<!-- one subprojects:end -->

## Workspace conventions

- Sub-projects live under ` + "`apps/*`" + `, ` + "`services/*`" + `, or ` + "`packages/*`" + `. The full project list lives in ` + "`one.manifest.json`" + `.
- Use ` + "`one add <template-id> --name <name>`" + ` to scaffold a new sub-project. The CLI updates the manifest and refreshes this file.
- Never commit ` + "`.env*`" + ` files. Use ` + "`one secrets set <KEY> --env <env>`" + ` and consume via ` + "`one secrets materialize`" + `.
- Conventional Commits (` + "`feat:`" + `, ` + "`fix:`" + `, ` + "`refactor:`" + ` ...) — one commit = one logical change.
- Don't hand-edit the managed blocks below. They are regenerated by the CLI; if they're wrong, re-run ` + "`one add`" + ` or ` + "`one ai refresh`" + `.

## Per-template AI provider guides

The block below aggregates each template's ` + "`ai/common.md`" + ` content and is filled by ` + "`one ai refresh`" + ` for every supported AI provider (current workspaces always render both AGENTS.md and CLAUDE.md).

<!-- one ai-guides:start -->
*No sub-projects yet. Run* ` + "`one add <template-id> --name <name>`" + ` *to scaffold one — the workspace's ` + "`AGENTS.md`" + ` and ` + "`CLAUDE.md`" + ` will be regenerated automatically.*
<!-- one ai-guides:end -->
`

// buildClaudeMd renders the workspace CLAUDE.md skeleton with the given
// project name in the title.
func buildClaudeMd(projectName string) string {
	return fmt.Sprintf(claudeMdTemplate, projectName)
}

// changesetConfig is the .changeset/config.json scaffolders write at
// create time. Encoded as orderedJSON so json.MarshalIndent preserves
// the field order below.
var changesetConfig = orderedJSON{
	{Key: "$schema", Value: "https://unpkg.com/@changesets/config@3.1.1/schema.json"},
	{Key: "changelog", Value: "@changesets/cli/changelog"},
	{Key: "commit", Value: false},
	{Key: "fixed", Value: []any{}},
	{Key: "linked", Value: []any{}},
	{Key: "access", Value: "restricted"},
	{Key: "baseBranch", Value: "main"},
	{Key: "updateInternalDependencies", Value: "patch"},
	{Key: "ignore", Value: []any{}},
}

// Package manager spec strings shipped in the workspace-root
// package.json.
const (
	packageManagerName = "pnpm"
	packageManagerSpec = "pnpm@10.14.0"
)

// buildPackageJSON returns the workspace root package.json. Workspace-scope
// One configuration moved into one.manifest.json in v2 — this file is now
// a plain pnpm root with no `one` block.
func buildPackageJSON(name string) orderedJSON {
	return orderedJSON{
		{Key: "name", Value: name},
		{Key: "private", Value: true},
		{Key: "version", Value: "0.0.0"},
		{Key: "packageManager", Value: packageManagerSpec},
		{Key: "scripts", Value: orderedJSON{
			{Key: "prepare", Value: "husky"},
			{Key: "changeset", Value: "changeset"},
		}},
		{Key: "devDependencies", Value: orderedJSON{
			{Key: "@changesets/cli", Value: "latest"},
			{Key: "@commitlint/cli", Value: "latest"},
			{Key: "@commitlint/config-conventional", Value: "latest"},
			{Key: "husky", Value: "latest"},
		}},
	}
}

// emptyManifest is the freshly-stamped one.manifest.json. Carries
// only the workspace identity (workspace.id + workspace.name) and an
// empty projects array; backend selections (env / deploy / container)
// land later via `env init`, `one add`, etc.
func emptyManifest(projectName string) orderedJSON {
	return orderedJSON{
		{Key: "version", Value: workspace.ManifestVersion},
		{Key: "workspace", Value: orderedJSON{
			{Key: "id", Value: workspace.GenerateProjectID(projectName)},
			{Key: "name", Value: projectName},
		}},
		{Key: "projects", Value: []any{}},
	}
}
